#!/bin/bash

set -e

MYSQL_USER="root"

function drop_database {
  mysql -u$MYSQL_USER<<-EOL
    DROP DATABASE $1;
EOL
  [[ $? -eq 0 ]] && echo "Dropped database $1"
}

function create_database {
  mysql -u$MYSQL_USER<<-EOL
    CREATE DATABASE $1;
EOL
  [[ $? -eq 0 ]] && echo "Created database $1"
}

DATABASE_NAMES=( "kenfos" "kenfos_integration_test" )

for name in "${DATABASE_NAMES[@]}"; do
  database="${name}"
  drop_database $database || echo "Cannot drop database $database"
  create_database $database || echo "Cannot create database $database"
done
