liquibase:
  changeLog: classpath:/uk/co/kenfos/migration/changelog.yml

logging:
  level.org.springframework.boot.context: WARN
  level.org.springframework.context: WARN
  level.org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean: WARN

server.port: 8080

kenfos:
  payment-service:
    url: http://payment-api:9999

management.security.enabled: false

---
spring:
  groovy.template.check-template-location: false
  jpa.hibernate.ddl-auto: none
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://delivery-api-db:3306/kenfos?useSSL=false&nullNamePatternMatchesAll=true
    username: root
    password: ''

---
spring:
  profiles: h2-db
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:kenfos
    username: sa
    password: ''
